# Generated by Django 5.0.4 on 2025-03-26 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_dragon_modified_at_alter_house_modified_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='birth_date',
            field=models.DateField(default=datetime.date(2025, 3, 26)),
        ),
    ]
