# Generated by Django 5.0.4 on 2025-03-20 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_astronaut_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronaut',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='astronauts',
            field=models.ManyToManyField(related_name='missions', to='main_app.astronaut'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='spacecraft',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
