# Generated by Django 5.0.4 on 2025-02-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_product_category_alter_product_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('department', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=80)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('full_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
