# Generated by Django 5.0.4 on 2025-02-19 17:19

from django.db import migrations

def add_full_name(apps, schema_editor):
    Employee = apps.get_model('main_app', 'Employee')
    for e in Employee.objects.all():
        e.full_name = f'{e.first_name} {e.last_name}'
        e.save()

def remove_full_name(apps, schema_editor):
    Employee = apps.get_model('main_app', 'Employee')
    for e in Employee.objects.all():
        e.full_name = ''
        e.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_employee'),
    ]

    operations = [
        migrations.RunPython(add_full_name, reverse_code=remove_full_name)
    ]

