# Generated by Django 5.0.4 on 2025-02-19 17:24
import random

from django.db import migrations


def add_unique_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    all_products = Product.objects.all()
    barcodes = random.sample(range(100000000, 999999999), len(all_products))
    for i, product in enumerate(all_products):
        product.barcode = barcodes[i]
        product.save()

def reverse_add_unique_barcode(apps, schema_editor):
    Product = apps.get_model('main_app', 'Product')
    for p in Product.objects.all():
        p.barcode = 0
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_product_barcode'),
    ]

    operations = [
        migrations.RunPython(add_unique_barcode, reverse_code=reverse_add_unique_barcode),
    ]
