# Generated by Django 4.2.23 on 2025-06-19 05:21

import django.core.validators
from django.db import migrations, models
import traveler.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(help_text='*Nicknames can contain only letters and digits.', max_length=30, unique=True, validators=[django.core.validators.MinLengthValidator(3), traveler.validators.NicknameValidator()])),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('country', models.CharField(max_length=3)),
                ('about_me', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
