# Generated by Django 5.0.4 on 2025-03-25 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_quest_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quest',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='main_app.house'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
