# Generated by Django 5.0.4 on 2025-02-22 09:09

from django.db import migrations
from django.db.models import F, Case, When, Value
from django.db.models.functions import Length


def create_new_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    SmartphoneModel.objects.update(
        price=Length(F("brand")) * 120
    )

def set_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    SmartphoneModel.objects.update(
        category=Case(
            When(price__gte=750, then=Value("Expensive")),
            When(price__lt=750, then=Value("Cheap")),
    ))

def set_category_by_price(apps, schema_editor):
    create_new_price(apps, schema_editor)
    set_category(apps, schema_editor)

def reverse_price(apps, schema_editor):
    DEFAULT_PRICE = 0
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    SmartphoneModel.objects.bulk_update(price=DEFAULT_PRICE)

def reverse_category(apps, schema_editor):
    DEFAULT_CATEGORY = "No category"
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    SmartphoneModel.objects.bulk_update(category=DEFAULT_CATEGORY)

def reverse_category_by_price(apps, schema_editor):
    reverse_category(apps, schema_editor)
    reverse_price(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_smartphone'),
    ]

    operations = [
        migrations.RunPython(
            code=set_category_by_price,
            reverse_code=reverse_category_by_price
        )
    ]
