# Generated by Django 5.1.6 on 2025-02-28 17:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_studentenrollment_enrollment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturerprofile',
            name='lecturer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.lecturer'),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 28, 17, 32, 15, 415749, tzinfo=datetime.timezone.utc)),
        ),
    ]
