# Generated by Django 5.0.4 on 2025-02-20 13:40

from django.db import migrations


def migrate_unique_brands(apps, schema_editor):
    # Import models
    Shoe = apps.get_model('main_app', 'Shoe')
    UniqueBrands = apps.get_model('main_app', 'UniqueBrands')

    # prepare data for insertion
    unique_brand_names = Shoe.objects.all().values_list('brand', flat=True).distinct()
    add_unique_brands = [UniqueBrands(brand_name=brand_name) for brand_name in unique_brand_names]

    # Create the objects at once
    UniqueBrands.objects.bulk_create(add_unique_brands)

def remove_unique_brands(apps, schema_editor):
    UniqueBrands = apps.get_model('main_app', 'UniqueBrands')

    UniqueBrands.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uniquebrands'),
    ]

    operations = [
        migrations.RunPython(migrate_unique_brands, reverse_code=remove_unique_brands)
    ]
