# Generated by Django 5.0.4 on 2025-02-22 08:41

from django.db import migrations
from django.db.models import Case, When,Value


def create_age_group(apps, schema_editor):
    PersonModel = apps.get_model('main_app', 'Person')

    PersonModel.objects.update(
        age_group=Case(
            When(age__lte=12, then=Value("Child")),
            When(age__gte=18, then=Value("Adult")),
            default=Value("Teen"),
        )
    )

def reverse_age_group(apps, schema_editor):
    DEFAULT_AGE_GROUP = "No age group"

    PersonModel = apps.get_model('main_app', 'Person')

    PersonModel.objects.all().update(age_group=DEFAULT_AGE_GROUP)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_person'),
    ]

    operations = [
        migrations.RunPython(
            code=create_age_group,
            reverse_code=reverse_age_group
        )
    ]
