# Generated by Django 5.0.4 on 2025-02-22 08:52

from django.db import migrations
from django.db.models import Case, When, Value


def set_rarity(apps, schema_editor):
    ItemModel = apps.get_model('main_app', 'Item')

    ItemModel.objects.update(
        rarity=Case(
            When(price__lte=10, then=Value("Rare")),
            When(price__lte=10, then=Value("Rare")),
            When(price__gte=11, price__lte=20, then=Value("Very Rare")),
            When(price__gte=21, price__lte=30, then=Value("Extremely Rare")),
            When(price__gte=31, then=Value("Mega Rare")),
        )
    )

def reverse_rarity(apps, schema_editor):
    DEFAULT_RARITY = "No rarity"

    ItemModel = apps.get_model('main_app', 'Item')

    ItemModel.objects.all().update(rarity=DEFAULT_RARITY)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_item'),
    ]

    operations = [
        migrations.RunPython(
            code=set_rarity,
            reverse_code=reverse_rarity,
        )
    ]
