# Generated by Django 5.0.4 on 2025-02-22 09:45

from django.db import migrations
from django.db.models import Case, When, Value


def modify_delivery_and_warranty(apps, schema_editor):
    Order = apps.get_model('main_app', 'Order')

    # Order.objects.update(
    #     warranty=Case(
    #         When(status=='')
    #     )
    # )





class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_order'),
    ]

    operations = [
    ]
